### ISSUE TITLE
Fabric port for this amazing mod, please!!

### ISSUE THREAD

**Issue by ZpippoZ** [E1thanz/OREutils#2]
Since this mod is for Forge only I'm asking for a Fabric port. Who uses Forge anyways??

**Comment by E1thanz** [comment]
i will

**Comment by ZpippoZ** [comment]
Soon™?

**Comment by ZpippoZ** [comment]
Hey! Has progress been made on this?

**Comment by E1thanz** [comment]
no :]
im lazy

**Comment by ZpippoZ** [comment]
> no :] im lazy

Hi lazy

**Comment by ZpippoZ** [comment]
make progress dummy

**Comment by ZpippoZ** [comment]
ok noob
